# syntax=docker/dockerfile:experimental

FROM docker-registry.kabala.tech/node12-with-git:latest

ARG GH_TOKEN

WORKDIR /app

COPY . .

RUN yarn

RUN yarn workspaces run prepare

RUN git checkout master

RUN git status

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh lerna publish
