export const wrap: string;
export const wrapOpen: string;
export const categoryIcon: string;
export const link: string;
export const icon: string;
export const title: string;
export const isNew: string;
export const submenuWrap: string;
export const submenu: string;
